export const ADD_FAVORITE_LAUNCH = 'ADD_FAVORITE_LAUNCH';
export const REMOVE_FAVORITE_LAUNCH = 'REMOVE_FAVORITE_LAUNCH';
export const ADD_FAVORITE_LAUNCHPAD = 'ADD_FAVORITE_LAUNCHPAD';
export const REMOVE_FAVORITE_LAUNCHPAD = 'REMOVE_FAVORITE_LAUNCHPAD';
export const UPDATE_SORT = 'UPDATE_SORT';
export const SET_GRIDVIEW = 'SET_GRIDVIEW';
export const SET_LISTVIEW = 'SET_LISTVIEW';
export const UPDATE_FILTERS = 'UPDATE_FILTERS';
